eCommerce/Cart/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name="Cart"

urlpatterns = [
    path("cart_view/",views.cart_view,name="cart_view"),
    path("add_to_cart/<str:pk>",views.add_to_cart,name="add_cart"),
    path("delete_cart_item/<str:pk>",views.delete_cart_item,name="delete_cart_item"),
    path("delete_cart/<str:pk>",views.delete_cart,name="delete_cart"),
    path("order_form",views.orderform,name="orderform"),
    path("order-view",views.orderview,name="order-view"),
    path("payment_status<str:uname>",views.payment_status,name="status"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/Shop/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='Shop'
urlpatterns = [
    path('',views.categories,name='categories'),
    path('search',views.searchitem,name='search'),
    path('add_category',views.add_category,name='add_category'),
    path('add_product',views.add_product,name='add_product'),
    path('product/<str:pk>',views.product,name='product'),
    path('detail/<str:pk>',views.productdetail,name='detail'),
    path('add_stock/<str:pk>',views.add_stock,name='add_stock'),
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eCommerce/eCommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls')),
    path('cart/',include('Cart.urls')),
]

eCommerce/Cart/models.py
from django.db import models
from Shop.models import Product
from django.contrib.auth.models import User
# Create your models here.


class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    add_on=models.DateTimeField(auto_now_add=True)


    def total_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

class OrderDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.TextField()
    no_of_items = models.PositiveIntegerField()
    phone = models.CharField(max_length=15)
    pin = models.CharField(max_length=10)

    order_id =  models.CharField(max_length=30)
    payment_status = models.CharField(max_length=30,default="Pending")
    delivery_status = models.CharField(max_length=30,default="Pending")
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.order_id

class Payment(models.Model):
    name = models.CharField(max_length=30)
    amount = models.IntegerField()
    order_id = models.CharField(max_length=30)
    razorpay_payment_id = models.CharField(max_length=30, blank=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

eCommerce/Cart/views.py
import razorpay
from django.shortcuts import render,redirect
from .models import Cart,Payment,OrderDetail,User
from Shop.models import Product
from django.db.models import Aggregate,Sum,F
from django.contrib import messages

# Create your views here.
def add_to_cart(request,pk):
    product=Product.objects.get(id=pk)
    user= request.user
    if product.stock < 0:
        messages.error(request,"The product is out of stock")
        return redirect("Cart:cart_view")
    try:
        cart_item=Cart.objects.get(product=product,user=user)
        cart_item.quantity +=1
        cart_item.save()

    except:
        cart_item = Cart.objects.create(product=product, user=user, quantity=1)
        product.stock -= 1
        product.save()
        cart_item.save()

    return redirect("Cart:cart_view")

def cart_view(request):
    user=request.user
    cart=Cart.objects.filter(user=user)
    cart = cart.annotate(total_price=F('quantity') * F('product__price'))
    total=cart.aggregate(total=Sum('total_price'))['total'] or 0
    context={
        "cart":cart,
        "total":total
    }
    return render(request,"cart_view.html",context)

def delete_cart_item(request,pk):
    user=request.user
    product=Product.objects.get(id=pk)
    cart=Cart.objects.get(user=user,product=product)
    try:
        if cart.quantity > 1: #checking if quantity is greater than 0
            cart.quantity -=1
            product.stock +=1
            product.save()
            cart.save()
        else: # if quantity becomes 0
            cart.delete() #delete cart product
            product.stock +=1 #adding last 1 stock when cart is deleted
            product.save() # saving the changes
    except:
        pass
    return redirect("Cart:cart_view")

def delete_cart(request):
    user = request.user
    product = Product.objects.get(id=pk)
    try:
        cart = Cart.objects.get(user=user, product=product)
        cart.delete()
        cart.save()
    except:
        pass
    return redirect("Cart:cart_view")

def orderform(request):
    if request.method == 'POST':
        address=request.POST['address']
        phone = request.POST['phone']
        pin = request.POST['pin']

        total=0
        user = request.user
        cart = Cart.objects.filter(user=user).select_related('product')
        total = sum(item.product.price * item.quantity for item in cart)
        print(total)

        #razorpay conenction
        client=razorpay.Client(auth=('rzp_test_4dDYIqQwrl8aCV','T92lz9vhN9VcQuK32XECjC4b'))

        #razorpay order creation
        response_payment=client.order.create(dict(amount=total*100,currency='INR'))
        order_id=response_payment['id'] #return order id
        print(order_id)
        status = response_payment['status'] #return the status from response
        print(status)
        if status=="created":
            payments=Payment.objects.create(name=user.username,amount=total,order_id=order_id)
            payments.save()
            print(payments)

            for order in cart:
                orders=OrderDetail.objects.create(product=order.product,user=order.user,address=address,phone=phone,pin=pin,no_of_items=order.quantity,order_id=order_id)
                # o = orderdetails.objects.create(product=i.product, user=i.user, phone=pn, address=a, pincode=n,orderid=order_id)
                # o.save()
                orders.save()
            context={
                'payment':response_payment,
                'name':user.username
            }
            return render(request,'payment.html',context)
    return render(request,'orderform.html')



from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login
@csrf_exempt
def payment_status(request,uname):
    user=User.objects.get(username=uname) #getting user info
    login(request,user)

    response=request.POST #respose after payment successful
    #check the validity of payment deatils from razorpay
    param_dict={
        'razorpay_order_id':response['razorpay_order_id'],
        'razorpay_payment_id':response['razorpay_payment_id'],
        'razorpay_signature':response['razorpay_signature'],
    }
    client=razorpay.Client(auth=('rzp_test_4dDYIqQwrl8aCV','T92lz9vhN9VcQuK32XECjC4b'))
    try:
        #function to check the payment is valid and verify the payment
        status=client.utility.verify_payment_signature(param_dict)
        payment=Payment.objects.get(order_id=response['razorpay_order_id'])

        payment.razorpay_payment_id=response['razorpay_payment_id']
        payment.paid=True
        payment.save()

        orders=OrderDetail.objects.filter(order_id=response['razorpay_order_id']).select_related('product')
        for order in orders:
            order.payment_status='completed'
            order.save()
        # delete cart after the payment is succesfull for that particular user
        cart=Cart.objects.filter(user=user)
        cart.delete()

    except:
        pass

    return render(request, "payment_status.html", context={"status": status})


def orderview(request):
    user=request.user
    order_detail = OrderDetail.objects.filter(payment_status='completed').select_related('user')
    print(order_detail)
    # order_total= OrderDetail.objects.filter(order_id=order_detail.order_id,payment_status='completed').select_related('user')
    context={
        'orders':order_detail
    }
    return render(request,'orderview.html',context)

eCommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">

<head>
	<title></title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="format-detection" content="telephone=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="author" content="">
	<meta name="keywords" content="">
	<meta name="description" content="">


	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"/>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'icomoon/icomoon.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/vendor.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

</head>

<body data-bs-spy="scroll" data-bs-target="#header" tabindex="0">

	<div id="header-wrap">

		<div class="top-content">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-6">
						<div class="social-links">
							<ul>
								<li>
									<a href="#"><i class="icon icon-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="icon icon-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="icon icon-youtube-play"></i></a>
								</li>
								<li>
									<a href="#"><i class="icon icon-behance-square"></i></a>
								</li>
							</ul>
						</div><!--social-links-->
					</div>
					<div class="col-md-6">
						<div class="right-element">
							{% if not user.is_authenticated %}
							<a href="{% url 'Shop:register' %}" class="user-account for-buy"><i
									class="icon icon-user"></i><span>Register</span></a>
							<a href="{% url 'Shop:login' %}" class="user-account for-buy"><i
									class="icon icon-user"></i><span>Login</span></a>
							{% else %}
							<a href="{% url 'Shop:logout' %}" class="user-account for-buy"><i
									class="icon icon-user"></i><span>Logout</span></a>
							<div class="action-menu">

								<div class="search-bar">
									<a href="#" class="search-button search-toggle" data-selector="#header-wrap">
										<i class="icon icon-search"></i>
									</a>
									<form role="search" method="POST" action="{% url 'Shop:search' %}" class="search-box">
										{% csrf_token %}
										<input class="search-field text search-input" placeholder="Search"  name="search" type="search">
									</form>
								</div>
							</div>
							{% endif %}
<!--							<a href="#" class="cart for-buy"><i class="icon icon-clipboard"></i><span>Cart:(0-->
<!--									$)</span></a>-->



						</div><!--top-right-->
					</div>

				</div>
			</div>
		</div><!--top-content-->
	</div>

		<header id="header">
    <div class="container fs-5">
        <div class="row">
            <div class="col-sm-12 d-flex justify-content-center"> <!-- Changed to full width and added flexbox class -->
                <nav id="navbar">
                    <div class="main-menu stellarnav">
                        <ul class="d-flex justify-content-evenly menu-list "> <!-- Added flexbox class for horizontal alignment -->
							<li class="menu-item active"><a href="{% url 'Shop:categories' %}">Home</a></li>
						{% if user.is_authenticated %}
							{% if user.is_superuser %}
							<li class="menu-item has-sub">
									<a href="#pages" class="nav-link">Add</a>
									<ul>
										<li class="menu-item"><a href="{% url 'Shop:add_category' %}">Category</a></li>
										<li class="menu-item"><a href="{% url 'Shop:add_product' %}">Product</a></li>
									</ul>
								 </li>
							<li class="menu-item has-sub">
								<a href="#pages" class="nav-link">Category</a>
							<ul>
									{% for i in links %}
									<li class="menu-item"><a href="{% url 'Shop:product' i.id %}">{{ i.name }}</a></li>
									{% endfor %}
							</ul>
							</li>
							{% else %}
								<li class="menu-item has-sub">
								<a href="#pages" class="nav-link">Category</a>
							<ul>
									{% for i in links %}
									<li class="menu-item"><a href="{% url 'Shop:product' i.id %}">{{ i.name }}</a></li>
									{% endfor %}
							</ul>
							</li>
							{% endif %}
						{% endif %}
					  	<li class="menu-item"><a href="#featured-books" class="nav-link">Featured</a></li>
						{% if user.is_authenticated %}
							{% if not user.is_superuser %}
							 <li class="menu-item"><a href="{% url 'Cart:cart_view' %}" class="cart for-buy nav-link"><i class="icon icon-clipboard"><sup>{{count}}</sup></i>Cart(₹ {{total}})</a></li>
							 <li class="menu-item"><a href="{% url 'Cart:order-view' %}">Your orders</a></li>
                        </ul>
						{% endif %}
						{% endif %}
                        <div class="hamburger">
                            <span class="bar"></span>
                            <span class="bar"></span>
                            <span class="bar"></span>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}

	<footer id="footer">
		<div class="container">
			<div class="row">

				<div class="col-md-4">

					<div class="footer-item">
						<div class="company-brand">
<!--							<img src="{% static 'images/main-logo.png' %}" alt="logo" class="footer-logo">-->
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis sed ptibus liberolectus
								nonet psryroin. Amet sed lorem posuere sit iaculis amet, ac urna. Adipiscing fames
								semper erat ac in suspendisse iaculis.</p>
						</div>
					</div>

				</div>

				<div class="col-md-2">

					<div class="footer-menu">
						<h5>About Us</h5>
						<ul class="menu-list">
							<li class="menu-item">
								<a href="#">vision</a>
							</li>
							<li class="menu-item">
								<a href="#">articles </a>
							</li>
							<li class="menu-item">
								<a href="#">careers</a>
							</li>
							<li class="menu-item">
								<a href="#">service terms</a>
							</li>
							<li class="menu-item">
								<a href="#">donate</a>
							</li>
						</ul>
					</div>


				</div>
				<div class="col-md-2">

					<div class="footer-menu">
						<h5>Discover</h5>
						<ul class="menu-list">
							<li class="menu-item">
								<a href="#">Home</a>
							</li>
							<li class="menu-item">
								<a href="#">Books</a>
							</li>
							<li class="menu-item">
								<a href="#">Authors</a>
							</li>
							<li class="menu-item">
								<a href="#">Subjects</a>
							</li>
							<li class="menu-item">
								<a href="#">Advanced Search</a>
							</li>
						</ul>
					</div>

				</div>
				<div class="col-md-2">

					<div class="footer-menu">
						<h5>My account</h5>
						<ul class="menu-list">
							<li class="menu-item">
								<a href="#">Sign In</a>
							</li>
							<li class="menu-item">
								<a href="#">View Cart</a>
							</li>
							<li class="menu-item">
								<a href="#">My Wishtlist</a>
							</li>
							<li class="menu-item">
								<a href="#">Track My Order</a>
							</li>
						</ul>
					</div>

				</div>
				<div class="col-md-2">

					<div class="footer-menu">
						<h5>Help</h5>
						<ul class="menu-list">
							<li class="menu-item">
								<a href="#">Help center</a>
							</li>
							<li class="menu-item">
								<a href="#">Report a problem</a>
							</li>
							<li class="menu-item">
								<a href="#">Suggesting edits</a>
							</li>
							<li class="menu-item">
								<a href="#">Contact us</a>
							</li>
						</ul>
					</div>

				</div>

			</div>
			<!-- / row -->

		</div>
	</footer>

	<div id="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="copyright">
						<div class="row">

							<div class="col-md-6">
								<p>© 2022 All rights reserved. Free HTML Template by <a
										href="https://www.templatesjungle.com/" target="_blank">TemplatesJungle</a></p>
							</div>

							<div class="col-md-6">
								<div class="social-links align-right">
									<ul>
										<li>
											<a href="#"><i class="icon icon-facebook"></i></a>
										</li>
										<li>
											<a href="#"><i class="icon icon-twitter"></i></a>
										</li>
										<li>
											<a href="#"><i class="icon icon-youtube-play"></i></a>
										</li>
										<li>
											<a href="#"><i class="icon icon-behance-square"></i></a>
										</li>
									</ul>
								</div>
							</div>

						</div>
					</div><!--grid-->

				</div><!--footer-bottom-content-->
			</div>
		</div>
	</div>

	<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
		crossorigin="anonymous"></script>
	<script src="{% static 'js/plugins.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
</body>

</html>

eCommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .img-fluid {
        height: auto; /* Maintain aspect ratio */
    }
</style>
<section id="billboard">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <button class="prev slick-arrow">
                    <i class="icon icon-arrow-left"></i>
                </button>

                <div class="main-slider pattern-overlay">
                    <div class="slider-item d-flex align-items-center">
                        <div class="banner-content">
                            <h2 class="banner-title">Google Pixel</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu feugiat amet, libero
                                ipsum enim pharetra hac. Urna commodo, lacus ut magna velit eleifend. Amet, quis
                                urna, a eu.</p>
                            <div class="btn-wrap">
                                <a href="#" class="btn btn-outline-accent btn-accent-arrow">Read More<i
                                        class="icon icon-ns-arrow-right"></i></a>
                            </div>
                        </div><!--banner-content-->
                        <img src="{% static 'images/phone banner.jpg' %}" alt="banner" class="img-fluid mb-5" style="width:20%">
                    </div><!--slider-item-->

                    <div class="slider-item d-flex align-items-center">
                        <div class="banner-content">
                            <h2 class="banner-title">Casuals and Formals</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu feugiat amet, libero
                                ipsum enim pharetra hac. Urna commodo, lacus ut magna velit eleifend. Amet, quis
                                urna, a eu.</p>
                            <div class="btn-wrap">
                                <a href="#" class="btn btn-outline-accent btn-accent-arrow">Read More<i
                                        class="icon icon-ns-arrow-right"></i></a>
                            </div>
                        </div><!--banner-content-->
                        <img src="{% static 'images/cloths banner.jpg' %}" alt="banner" class="img-fluid mb-5" style="width:20%">
                    </div><!--slider-item-->

                    <div class="slider-item d-flex align-items-center">
                        <div class="banner-content">
                            <h2 class="banner-title">Fresh and Safe</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu feugiat amet, libero
                                ipsum enim pharetra hac. Urna commodo, lacus ut magna velit eleifend. Amet, quis
                                urna, a eu.</p>
                            <div class="btn-wrap">
                                <a href="#" class="btn btn-outline-accent btn-accent-arrow">Read More<i
                                        class="icon icon-ns-arrow-right"></i></a>
                            </div>
                        </div><!--banner-content-->
                        <img src="{% static 'images/grocery_banner.jpg' %}" alt="banner" class="img-fluid mb-5" style="width:20%">
                    </div><!--slider-item-->

                </div><!--slider-->

                <button class="next slick-arrow">
                    <i class="icon icon-arrow-right"></i>
                </button>

            </div>
        </div>
    </div>
</section>

	<section id="featured-books" class="py-5 my-5">
		<div class="container">
			<div class="row">
				<div class="col-md-12">

					<div class="section-header align-center">
						<div class="title">
							<span>Some quality items</span>
						</div>
						<h2 class="section-title">Our Collections</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
							Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
							when an unknown printer took a galley of type and scrambled it to make a type
							specimen book. It has survived not only five centuries, but also the leap into
							electronic typesetting, remaining essentially unchanged. It was popularised in
							the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
							and more recently with desktop publishing software like Aldus PageMaker including
							versions of Lorem Ipsum.</p>
					</div>

					<div class="product-list" data-aos="fade-up">
						<div class="row">

<!--							<div class="col-md-3">-->
<!--								<div class="product-item">-->
<!--									<figure class="product-style">-->
<!--										<img src="{% static 'images/product-item1.jpg' %}" alt="Books" class="product-item">-->
<!--										<button type="button" class="add-to-cart" data-product-tile="add-to-cart">Add to-->
<!--											Cart</button>-->
<!--									</figure>-->
<!--&lt;!&ndash;									<figcaption>&ndash;&gt;-->
<!--&lt;!&ndash;										<h3>Simple way of piece life</h3>&ndash;&gt;-->
<!--&lt;!&ndash;										<span>Armor Ramsey</span>&ndash;&gt;-->
<!--&lt;!&ndash;										<div class="item-price">$ 40.00</div>&ndash;&gt;-->
<!--&lt;!&ndash;									</figcaption>&ndash;&gt;-->
<!--								</div>-->
<!--							</div>-->
							{% for items in categories %}
							<div class="col-4">
								<div class="product-item">
									<figure class="product-style">
										<img src="{{items.img.url}}" alt="products" class="product-item" style="height:365px;">
										<a href="{% url 'Shop:product' items.id %}"><button type="button" class="add-to-cart">Go to {{items.name}}</button></a>
									</figure>
									<figcaption>
										<h3>{{items.name}}</h3>
<!--										<span>Sanchit Howdy</span>-->
<!--										<div class="item-price">$ 38.00</div>-->
									</figcaption>
								</div>
							</div>
							{% endfor %}

<!--							<div class="col-md-3">-->
<!--								<div class="product-item">-->
<!--									<figure class="product-style">-->
<!--										<img src="{% static 'images/product-item3.jpg' %}" alt="Books" class="product-item">-->
<!--										<button type="button" class="add-to-cart" data-product-tile="add-to-cart">Add to-->
<!--											Cart</button>-->
<!--									</figure>-->
<!--&lt;!&ndash;									<figcaption>&ndash;&gt;-->
<!--&lt;!&ndash;										<h3>The lady beauty Scarlett</h3>&ndash;&gt;-->
<!--&lt;!&ndash;										<span>Arthur Doyle</span>&ndash;&gt;-->
<!--&lt;!&ndash;										<div class="item-price">$ 45.00</div>&ndash;&gt;-->
<!--&lt;!&ndash;									</figcaption>&ndash;&gt;-->
<!--								</div>-->
<!--							</div>-->

<!--							<div class="col-md-3">-->
<!--								<div class="product-item">-->
<!--									<figure class="product-style">-->
<!--										<img src="{% static 'images/product-item4.jpg' %}" alt="Books" class="product-item">-->
<!--										<button type="button" class="add-to-cart" data-product-tile="add-to-cart">Add to-->
<!--											Cart</button>-->
<!--									</figure>-->
<!--&lt;!&ndash;									<figcaption>&ndash;&gt;-->
<!--&lt;!&ndash;										<h3>Once upon a time</h3>&ndash;&gt;-->
<!--&lt;!&ndash;										<span>Klien Marry</span>&ndash;&gt;-->
<!--&lt;!&ndash;										<div class="item-price">$ 35.00</div>&ndash;&gt;-->
<!--&lt;!&ndash;									</figcaption>&ndash;&gt;-->
<!--								</div>-->
<!--							</div>-->

						</div><!--ft-books-slider-->
					</div><!--grid-->


				</div><!--inner-content-->
			</div>

			<div class="row">
				<div class="col-md-12">

					<div class="btn-wrap align-right">
						<a href="#" class="btn-accent-arrow">View all products <i
								class="icon icon-ns-arrow-right"></i></a>
					</div>

				</div>
			</div>
		</div>
	</section>

{% endblock %}

eCommerce/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

	<section id="best-selling" class="leaf-pattern-overlay">
		<div class="corner-pattern-overlay"></div>
		<div class="container">
			<div class="row justify-content-center">

				<div class="col-md-8">

					<div class="row">

						<div class="col-md-6">
							<figure class="products-thumb">
								<img src="{{product.img.url}}" alt="book" class="single-image">
							</figure>
						</div>

						<div class="col-md-6">
							<div class="product-entry">
								<h2 class="section-title divider">{{product.name}}</h2>

								<div class="products-content">

									<h3 class="item-title">Specifications</h3>
									<p>{{product.des}}</p>
									<div class="author-name">{{product.stock}} left</div>
									<div class="item-price">₹ {{product.price}}</div>
								{% if user.is_superuser %} <!-- if user is admin -->
									{% if product.stock > 0 %} <!-- if stock is present -->
											<div class="btn-wrap">
												<div class="author-name">Product in Stock</div>
													<a	 href="{% url 'Shop:add_stock' product.id %}" class="btn-accent-arrow">Add stock<i class="icon icon-ns-arrow-right"></i></a>
											</div>
									{% else %}  <!-- if stock is empty -->
											<div class="author-name">Out of Stock</div>
												<div class="btn-wrap">
													<a href="{% url 'Shop:add_stock' product.id %}" class="btn-accent-arrow">Add stock<i class="icon icon-ns-arrow-right"></i></a>
											</div>

									{% endif %}  <!-- end if for stock -->
								{% else %}  <!-- if normal user -->
									{% if product.stock > 0 %} <!-- if stock is present -->
											<div class="btn-wrap">
												<div class="author-name">Product in Stock</div>
													<a href="{% url 'Cart:add_cart' product.id %}" class="btn btn-accent-arrow">Add to Cart<i class="icon icon-ns-arrow-right"></i></a>
											</div>
									{% else %}  <!-- if stock is empty -->
											<div class="author-name">Out of Stock</div>
<!--												<div class="btn-wrap">-->
<!--													<a href="#" class="btn-accent-arrow">Add stock<i class="icon icon-ns-arrow-right"></i></a>-->
											</div>
									{% endif %}

								{% endif %} <!-- end if for admin -->
								</div>

							</div>
						</div>

					</div>
					<!-- / row -->

				</div>

			</div>
		</div>
	</section>

{% endblock %}

eCommerce/templates/payment_status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if status %}
<div class="container mt-3 p-3 text-center" ><h1>payment success</h1></div>
{% else %}
<div class="container mt-3 p-3 text-center" ><h1>payment failed</h1></div>
{% endif %}
{% endblock %}