Libary/Books/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='Books'

urlpatterns = [
    path('',views.home,name='home'),
    path('add_book',views.add_book,name='add_book'),
    path('view_book',views.view_book,name='view_book'),
    path('details/<int:p>',views.details,name='details'),
    path('edit/<int:p>',views.edit,name='edit'),
    path('delete/<int:p>',views.delete,name='delete'),
    path('search',views.searchbook,name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Libary/Libary/urls.py
from django.contrib import admin
from django.urls import path,include
from Books import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Books.urls')),
    path('users/',include('Users.urls')),
]

Libary/Users/urls.py
from django.contrib import admin
from django.urls import path
from Users import views
app_name='Users'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
]

Libary/Books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=30) #
    author=models.CharField(max_length=50)
    Language=models.CharField(max_length=20)
    price=models.IntegerField() #number
    pages=models.IntegerField() #number
    cover=models.ImageField(upload_to='image') #image
    pdf=models.FileField(upload_to='pdf') #file

Libary/Users/models.py
from django.db import models

# Create your models here.

Libary/Books/views.py
from django.shortcuts import render,redirect
from .models import Book
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.
def home(request):
    return render(request,'home.html')
@login_required
def add_book(request):
    if(request.method=='POST'):
        title=request.POST['title']
        author=request.POST['author']
        language=request.POST['language']
        price=request.POST['price']
        pages=request.POST['pages']
        cover=request.FILES.get('cover') #FILE for image and documents
        pdf=request.FILES.get('pdf') #FILE for image and documents
        form=Book.objects.create(title=title,author=author,Language=language,price=price,pages=pages,cover=cover,pdf=pdf) #an new record is added
        form.save() #same as form.commit()
        return redirect('Books:view_book')

    return render(request,'add_book.html')
@login_required
def view_book(request):
    k=Book.objects.all() # same as select * from Books return all the data
    context={'book':k} #key value pair dictonary used to show values from views to html
    return render(request,'view_book.html',context)

def details(request,p):
    b=Book.objects.get(id=p)
    context={'book':b}
    return render(request,'details.html',context)

def edit(request,p):
    b=Book.objects.get(id=p)
    if(request.method=="POST"): #check if form is submitted

        b.title=request.POST["title"]
        b.author=request.POST['author']
        b.language=request.POST['language']
        b.pages=request.POST['pages']
        b.price=request.POST['price']
        if(request.FILES.get('cover'))==None:
            b.save()
        else:
            b.cover=request.FILES.get('cover')
        if(request.FILES.get('pdf'))==None:
            b.save()
        else:
            b.pdf=request.FILES.get('pdf')
        b.save()
        return redirect('Books:view_book')

    context={'book':b}
    return render(request,'edit.html',context)

def delete(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return redirect('Books:view_book')

def searchbook(request):
    b=None
    query=''
    if request.method=='POST':
        query=request.POST['search']
        if query:
            b=Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))# Q is used to when logical operation are needed in django application only after Q |,and,or are used

    return render(request,'search.html',{"search":b,"query":query})

Libary/Users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse

# Create your views here.
def register(request):
    if request.method=="POST":
        username=request.POST["username"]
        firstname=request.POST["firstname"]
        lastname=request.POST["lastname"]
        email=request.POST["email"]
        password=request.POST["pass1"]
        cpassword=request.POST["pass2"]
        if password==cpassword:
            u=User.objects.create_user(username=username,first_name=firstname,last_name=lastname,email=email,password=password)
            u.save()
        else:
            return HttpResponse("Password are not Matching try again")
        return redirect("Books:home")

    return render(request,'register.html')

def user_login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['pass1']

        user=authenticate(username=username,password=password)
        if user:
            login(request,user)
            return redirect('Books:home')
        else:
            return HttpResponse('<h1>invalid credentials</h1>')

    return  render(request,'login.html')

def user_logout(request):
    logout(request)
    return redirect('Users:login')

Libary/templates/add_book.html
{% extends 'base.html' %}
{% block content %}
<div class="container mb-3 w-50">
  <h1 class="text-center text-white">Add Book Page</h1>
  <form method="POST" class="text-white" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Book Name</label>
      <input type="text" class="form-control" name="title" placeholder="Enter Title" value="{{ request.POST.title }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Author</label>
      <input type="text" class="form-control" name="author" placeholder="Enter Author" value="{{ request.POST.author }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Language</label>
      <input type="text" class="form-control" name="language" placeholder="Enter Language" value="{{ request.POST.language }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Price</label>
      <input type="number" class="form-control" name="price" placeholder="Price.." value="{{ request.POST.price }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Pages</label>
      <input type="number" class="form-control" name="pages" placeholder="Pages.." value="{{ request.POST.pages }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Cover</label>
      <input type="file" class="form-control" name="cover">
    </div>

    <div class="mb-3">
      <label class="form-label">PDF</label>
      <input type="file" class="form-control" name="pdf">
    </div>

    <div class="mb-3 mx-auto text-center">
      <input class="btn btn-primary" type="submit" value="Submit">
    </div>

  </form>
</div>
{% endblock %}

Libary/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body style="background-image:url('{% static "images\bg.jpeg" %}');" >
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Libary App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'Books:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      {% if user.is_authenticated %} <!-- checking if user is logged in --->

      <li class="nav-item">
        <a class="nav-link" href="{% url 'Books:add_book' %}">Add books <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'Books:view_book' %}">View books <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active ">
        <a class="nav-link" href="{% url 'Users:logout' %}">Logout <span class="sr-only">(current)</span></a>
      </li>
      {% else %}

        <li class="nav-item active ">
        <a class="nav-link" href="{% url 'Users:register' %}">Register <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active ">
        <a class="nav-link" href="{% url 'Users:login' %}">Login <span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
    </ul>
    {% if user.is_authenticated %}
    <form class="d-flex" action="{% url 'Books:search' %}" method="POST">
      {% csrf_token %}
      <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit" >Search</button>
    </form>
    {% endif %}
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

Libary/templates/delete.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

Libary/templates/details.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center text-light">Details</h1>
<div class="container">
<div class="card mb-3 mx-auto" style="max-width: 50%;">
  <div class="row g-0">
  <div class="col-md-4 p-4">
  <img src="{{book.cover.url}}" class="card-img-top img-thumbnail" alt="...">
  </div>
  <div class="col-md-8">
  <div class="card-body p-3 ms-4">
    <h4 class="card-text mt-2 mb-2"><strong>Book</strong>: {{book.title}}</h4>
    <p class="card-text mb-3"><b>Author</b>: {{book.author}}</p>
    <p class="card-text mb-3"><b>Language</b>: {{book.Language}}</p>
    <p class="card-text mb-3"><b>Page</b>: {{book.pages}}</p>
    <p class="card-text mb-3"><b>Price</b>: {{book.price}}</p>
  </div>
  </div>
  </div>
</div>
</div>
{% endblock %}

Libary/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container mb-3 w-50">
  <h1 class="text-light text-center">Edit</h1>
  <form method="POST" class="text-white" enctype="multipart/form-data">

    <div class="mb-3">
      <label class="form-label">Book Name</label>
      <input type="text" class="form-control" name="title" placeholder="Enter Title" value="{{ book.title }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Author</label>
      <input type="text" class="form-control" name="author" placeholder="Enter Author" value="{{ book.author }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Language</label>
      <input type="text" class="form-control" name="language" placeholder="Enter Language" value="{{ book.Language }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Book Price</label>
      <input type="number" class="form-control" name="price" placeholder="Price.." value="{{ book.price }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Pages</label>
      <input type="number" class="form-control" name="pages" placeholder="Pages.." value="{{ book.pages }}">
    </div>

    <div class="mb-3">
      <label class="form-label">Cover</label>
      <input type="file" class="form-control" name="cover">
      <img src="{{ book.cover.url }}" width="100px" height="100px" class="mt-2">
    </div>

    <div class="mb-3">
      <label class="form-label">PDF</label>
      <input type="file" class="form-control" name="pdf">
      <a href="{{ book.pdf.url }}" class="mt-2">{{ book.pdf.url }}</a>
    </div>

    <div class="mb-3 mx-auto">
      <input class="btn btn-primary" type="submit" value="Submit">
    </div>
  </form>
</div>
{% endblock %}

Libary/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<h1 class="text-center text-white">Welcome {{user.username}},</h1>
{% else %}
<h1 class="text-center text-white">Welcome</h1>
{% endif %}
{% endblock %}
<!--<a href="{% url 'Books:home' %}" >Home</a>-->
<!--<a href="{% url 'Books:add_book' %}" >Add page</a>-->
<!--<a href="{% url 'Books:view_book' %}" >View page</a>-->
<!--<a href="{% url 'Users:register' %}" >Register user</a>-->
<!--<a href="{% url 'Users:login' %}" >Login user</a>-->

Libary/templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center text-white">Login</h1>
<div class="container mb-3 w-50">
  <form method="POST" class="text-white">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Enter the username">
    </div>

    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="pass1" placeholder="Enter The Password">
    </div>


    <div class="mb-3 mx-auto text-center">
      <input class="btn btn-primary" type="submit" value="Login">
    </div>

  </form>
</div>
{% endblock %}

Libary/templates/register.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center text-white">Register</h1>
<div class="container mb-3 w-50">
  <form method="POST" class="text-white">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Username</label>
      <input type="text" class="form-control" name="username" placeholder="Enter the username">
    </div>

    <div class="mb-3">
      <label class="form-label">First Name</label>
      <input type="text" class="form-control" name="firstname" placeholder="Enter First Name">
    </div>

    <div class="mb-3">
      <label class="form-label">Last Name</label>
      <input type="text" class="form-control" name="lastname" placeholder="Enter Last Name">
    </div>

    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" name="email" placeholder="Enter Email">
    </div>

    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="pass1" placeholder="Enter Password">
    </div>

    <div class="mb-3">
      <label class="form-label">Confirm Password</label>
      <input type="password" class="form-control" name="pass2" placeholder="Confirm Password">
    </div>

    <div class="mb-3 mx-auto text-center">
      <input class="btn btn-primary" type="submit" value="Register">
    </div>

  </form>
</div>
{% endblock %}

Libary/templates/search.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center text-white">Search Result</h1>

<div class="container mt-3 text-light">
  <h3>You have searched for <span class="text-light">{{query}}</span></h3>
  <div class="mx-auto w-75">
    {% if search == None %} <!-- if query is none-->
    <h4 class="text-danger text-center">No Result Found</h4>
    {% elif search.exists %}  <!-- if query is exists-->
<table class="table table-striped text-white table-bordered mx-auto">
  <thead>
    <tr>
      <th scope="col">Cover</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Language</th>
      <th scope="col">Price</th>
      <th scope="col">Page</th>
      <th scope="col">Pdf</th>

    </tr>
  </thead>
  <tbody>
  {%  for  i   in   search %}
    <tr>
      <td><img src="{{i.cover.url}}" height="150" width="100" class="img-thumbnail"></td>
      <td>{{i.title}}</td>
      <td>{{i.author}}</td>
      <td>{{i.Language}}</td>
      <td>{{i.price}}</td>
      <td>{{i.pages}}</td>
      <td><a href=" {{i.pdf.url}}">Download</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
    {% else %}
    <h4 class="text-danger text-center">No Result Found</h4>
    {% endif %}
  </div>
</div>
{% endblock %}

Libary/templates/view_book.html
{% extends 'base.html' %}
{% block content %}
<body>
<h1 class="text-center text-white">View book page</h1>
<div class="container mt-3 text-light">
<table class="table table-striped text-white table-bordered mx-auto">
  <thead>
    <tr>
      <th scope="col">Cover</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Language</th>
      <th scope="col">Price</th>
      <th scope="col">Page</th>
      <th scope="col">Pdf</th>
      <th scope="col">View</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>


    </tr>
  </thead>
  <tbody>
  {%  for  i   in   book %}
    <tr>
      <td><img src="{{i.cover.url}}" height="150" width="100" class="img-thumbnail"></td>
      <td>{{i.title}}</td>
      <td>{{i.author}}</td>
      <td>{{i.Language}}</td>
      <td>{{i.price}}</td>
      <td>{{i.pages}}</td>
      <td><a href=" {{i.pdf.url}}">Download</a></td>
      <td><a href="{% url 'Books:details' i.id %}" class="btn btn-primary text-light">View</a></td>
      <td><a href="{% url 'Books:edit' i.id %}"  class="btn btn-secondary text-light">Edit</a></td>
      <td><a href="{% url 'Books:delete' i.id %}" class="btn btn-danger text-light">delete</a></td>

    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<!--{% for i in book %}-->
<!--<ul class="text-white">-->
<!--  <li>{{i.id}}: Book Details</li>-->
<!--  <ul>-->
<!--    <li>{{i.title}}</li>-->
<!--    <li>{{i.author}}</li>-->
<!--    <li>{{i.Language}}</li>-->
<!--    <li>{{i.price}}</li>-->
<!--    <li>{{i.pages}}</li>-->
<!--    <li>{{i.cover}}</li>-->
<!--    <li>{{i.pdf}}</li>-->
<!--  </ul>-->
<!--</ul>-->
{% endfor %}
</body>
{% endblock %}